services:
  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: socialsphere-db
    environment:
      POSTGRES_DB: socialspheredb
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5432:5432"
    networks:
      - socialsphere-network

  # Spring Boot Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: socialsphere-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/socialspheredb
      DB_USER: spring
      DB_PASSWORD: spring
    depends_on:
      - db
    networks:
      - socialsphere-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: socialsphere-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - socialsphere-network

networks:
  socialsphere-network:
    driver: bridge